<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sharky\Sharky.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RLMatrix" Version="0.5.2" />
    <PackageReference Include="TorchSharp" Version="0.106.0" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>

</Project>
